name: deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: shadow-api
  ECS_CLUSTER: shadow-cluster
  ECS_SERVICE: shadow-api-service
  CONTAINER_NAME: shadow-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.5"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: login amazon ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build and push image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: download current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition shadow-api \
            --query taskDefinition \
            > task-definition.json

      - name: render new task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: run migrations
        run: |
          aws ecs run-task \
            --cluster $ECS_CLUSTER \
            --launch-type FARGATE \
            --task-definition shadow-api \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-0a6b550c424d7d716,subnet-0dd48025e5c659613],securityGroups=[sg-00a318a9fd18221f7],assignPublicIp=DISABLED}" \
            --overrides '{
              "containerOverrides": [
                {
                  "name": "shadow-api",
                  "command": [
                    "migrate",
                    "-path",
                    "internal/database/migrations",
                    "-database",
                    "postgres://'${{ secrets.DB_USER }}':'${{ secrets.DB_PASSWORD }}'@'${{ secrets.DB_HOST }}':'${{ secrets.DB_PORT }}'/'${{ secrets.DB_NAME }}'?sslmode='${{ secrets.DB_SSLMODE }}'",
                    "up"
                  ]
                }
              ]
            }'

      - name: deploy to ecs
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true